### ISSUE TITLE
Conformance Checklist

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/go-wfs#24]
__WFS3 Core Conformance Checklist__

Derived from the [WFS3 spec](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_requirement_class_core) as of 2018-03-15.

- (recommended) checkboxes aren't strictly necessary for conformanc
- (optional) checkboxes have value but may be ignored without problem

**7.2** API landing page
* [x] GET request at **/** served
* [x] Response content is based on [root.yaml](https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/root.yaml) and minimally includes links to:
    * [x] **/api**
    * [x] **/conformance**
    * [x] **/collections**

**7.3** API Definition
* [x] GET request at **/api** served
* [x] Response content is the api definition document
* [x] (recommended) Response content is OpenAPI format
* If multiple formats are provided, use content negotiation

**7.4** Declaration of conformance classes
* [x] GET request at **/conformance** served
* [x] Resonse content is based on OpenAPI schema [req-classes.yaml](https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/req-classes.yaml).
  * [x] conformsTo in response contains
    * [x] http://www.opengis.net/spec/wfs-1/3.0/req/core
    * [x] (recommended) http://www.opengis.net/spec/wfs-1/3.0/req/html
    * [x] (recommended) http://www.opengis.net/spec/wfs-1/3.0/req/geojson

**7.5** HTTP 1.1
* [x] Conforms to [HTTP 1.1](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#rfc2616), including correct use of status codes, headers, etc.
* [x] (recommended) Supports [entity tags](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#rfc2616)

**7.7** Support for cross-origin requests
* [x] (recommended) If the server will be accessed from the browser, allow cross-origin requests.

**7.8** Encodings
* [x] (recommended) HTML 1.1
* [x] (recommended) GeoJSON
* See [Media Types](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#mediatypes) for guidance
* For multiple encodings, the server needs a mechanism to mint encoding-specific links, such as /my/url.geojson or /my/url?f=geojson

**7.9** Coordinate reference systems
* [x] Geometries are served in WGS84 (EPSG/SRID 4326) unless another is requested.
* There is currently no mechanism to request another CRS.

**7.10** Link headers
* [x] All links in response payloads are included as Link headers as well.

**7.11** Feature collection**s** metadata
* [x] GET request at **/collections** served
* [x] Response content based on [content.yaml](https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/content.yaml)
* [x] Response "links" property includes:
  * [x] rel "self"
  * [x] rel "alternate" for each additional encoding available
  * [x] rel "item" for each collection available
  * [x] All links include "rel"
  * [x] All links include "type" specifying content type
  * [x] (recommended) For each external link defining structure or semantics of data contained in collections, include a link w/ rel "describedBy"
  * [x] For each supported encoding for each feature collection include an item with rel "item" in the "links" property.
* [x] Response "collections" property includes an entry for each feature collection.
* [x] If response provides an "extent" property it is formatted as a bounding box of the form [SWlong, SWlat, NElong, NElat]

**7.12** Feature collection metadata
* [x] GET request at **/collections/{name}** served
* [x] Response is metadata for the collection indicated using the same schema as in 7.11.

**7.13** Feature collections
* [x] GET request at **/collections/{name}/items** served
  * [x] "limit" querystring parameter indicating max number of features to provide at once.
    * [x] "limit" parameter includes "minimum" with value 1
    * [x] "limit" parameter includes (changeable) "default"
    * [x] "limit" parameter includes (changeable) "maximum"
  * [x] "bbox" querystring parameter.  Only features intersecting this rectangle are returned.
  * [x] "time" querystring parameter.  Feature collection must be time enabled.
  * [x] (recommended) For simple int/string properties of features include a querystring parameter with the property name to filter on.  For strings, wildcard matches may be useful in addition to simple equality.
* [x] Response includes links:
  * [x] rel "self"
  * [x] rel "alternate", one for every other content type
  * [x] (recommended) rel "next" for additional features beyond limit.
    * [x] "next" link uses same rules for "limit"
  * [x] (optional) rel "prev" to mirror functionality of "next"
  * [x] all links include "ref" & "type"
* Heads-up: details for timeStamp, numberMatched, numberReturned parameters are in the works.

**7.14** Feature
* [x] GET request at **/collections/{name}/items]{id}** served
* [x] Response payload contains the feature identified.
* [x] Response includes links:
  * [x] rel "self"
  * [x] rel "alternate" for other content types supported.
  * [x] rel "collection"
